/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mimvc.vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;

/**
 *
 * @author Patricio
 */
public class VistaMP extends javax.swing.JFrame {

    /**
     * Creates new form VistaMP
     */
    public VistaMP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        tlbMC = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        tlbMC1 = new javax.swing.JButton();
        tlbMC2 = new javax.swing.JButton();
        tlbMC3 = new javax.swing.JButton();
        Desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuClienteMantenimiento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        tlbMC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mimvc/vista/icons/user.png"))); // NOI18N
        tlbMC.setToolTipText("Mantenimiento de Clientes");
        tlbMC.setFocusable(false);
        tlbMC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlbMC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tlbMC);
        jToolBar1.add(jSeparator1);

        tlbMC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mimvc/vista/icons/maximize.png"))); // NOI18N
        tlbMC1.setFocusable(false);
        tlbMC1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlbMC1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tlbMC1);

        tlbMC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mimvc/vista/icons/save.png"))); // NOI18N
        tlbMC2.setFocusable(false);
        tlbMC2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlbMC2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tlbMC2);

        tlbMC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mimvc/vista/icons/time.png"))); // NOI18N
        tlbMC3.setFocusable(false);
        tlbMC3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlbMC3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tlbMC3);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jMenu1.setText("Clientes");

        mnuClienteMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mimvc/vista/icons/user.png"))); // NOI18N
        mnuClienteMantenimiento.setText("Mantenimiento");
        jMenu1.add(mnuClienteMantenimiento);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Productos");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
            .addComponent(Desktop)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JMenuItem getMnuClienteMantenimiento() {
        return mnuClienteMantenimiento;
    }

    public void setMnuClienteMantenimiento(JMenuItem mnuClienteMantenimiento) {
        this.mnuClienteMantenimiento = mnuClienteMantenimiento;
    }

    public JButton getTlbMC() {
        return tlbMC;
    }

    public void setTlbMC(JButton tlbMC) {
        this.tlbMC = tlbMC;
    }

    public JDesktopPane getDesktop() {
        return Desktop;
    }

    public void setDesktop(JDesktopPane Desktop) {
        this.Desktop = Desktop;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuClienteMantenimiento;
    private javax.swing.JButton tlbMC;
    private javax.swing.JButton tlbMC1;
    private javax.swing.JButton tlbMC2;
    private javax.swing.JButton tlbMC3;
    // End of variables declaration//GEN-END:variables
}
